
// This file has been generated by the GUI designer. Do not modify.
namespace ProtogameEditorHost
{
	public partial class HostWindow
	{
		private global::Gtk.GLWidget glWidget;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ProtogameEditorHost.HostWindow
			this.Name = "ProtogameEditorHost.HostWindow";
			this.Title = "Host Window";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ProtogameEditorHost.HostWindow.Gtk.Container+ContainerChild
			this.glWidget = new global::Gtk.GLWidget ();
			this.glWidget.Name = "glWidget";
			this.glWidget.SingleBuffer = false;
			this.glWidget.ColorBPP = 0;
			this.glWidget.AccumulatorBPP = 0;
			this.glWidget.DepthBPP = 0;
			this.glWidget.StencilBPP = 0;
			this.glWidget.Samples = 0;
			this.glWidget.Stereo = false;
			this.glWidget.GlVersionMajor = 0;
			this.glWidget.GlVersionMinor = 0;
			this.Add (this.glWidget);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
